apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: heart-disease-api
        static_configs:
          - targets: ["heart-disease-api-service:8000"]  # Match your API Service port
        metrics_path: /metrics  # Fixed path
        scheme: http